name: Do It

on:
  workflow_dispatch:
    inputs:
      destination:
        type: choice
        description: Where we want to deploy (US or EU).
        required: true
        default: 'US'
        options:
          - 'US'
          - 'EU'
          - 'Other'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Output stuff
        run: echo "Destination? ${{ inputs.destination }}"; \
             echo "Is EU? ${{ inputs.destination == 'EU' && 'Yes' || 'No' }}"; \
             echo "Is US? ${{ inputs.destination == 'US' && 'Yes' || 'No' }}"


