name: Do It

on:
  workflow_dispatch:
    inputs:
      destination:
        type: choice
        description: Where we want to deploy (US or EU).
        required: true
        default: 'US'
        options:
          - 'US'
          - 'EU'
          - 'Other'

jobs:
  test:
    steps:
      - name: Output stuff
        show_dest: echo "Destination? ${{ inputs.destination }}"
        show_iseu: echo "Is EU? ${{ inputs.destination == 'EU' && 'Yes' || 'No' }}"
        show_isus: echo "Is US? ${{ inputs.destination == 'US' && 'Yes' || 'No' }}"


