name: Deploy to Lambda

on:
  workflow_dispatch:
    inputs:
      region:
        description: The region we want to deploy to.
        required: true
        type: string
      environment:
        description: The environment to deploy to.
        required: true
        type: string
      is_eu:
        description: True if deploying to EU.
        required: false
        type: boolean

permissions:
  id-token: write
  contents: read

jobs:
  publish_lambda:
    name: Publish Lambda source code
    runs-on: ubuntu-latest
    steps:
      - name: Publish
        run: |
          echo "region $inputs.region"
          echo "super_region $super_region"
        env:
          super_region: "${{ inputs.region }} is super"

      - name: Publish Again
        run: |
          echo "region $inputs.region"
          echo "super_region $super_region"
